network:
  host: "localhost"
  port: 3000
  # Optional, enables the use of generating a link url with /authorize
  externalUrl:
db:
  url: "sqlite://file:tradecraft.db"
  username: ""
  password: ""
session:
  # Session controller, use 'memory' for a single-instance server
  type: "memory"
  cookie:
    # Require HTTPS for sessions
    secure: false
    # In seconds
    maxAge: 86400